# Generated by Django 5.0.4 on 2024-05-13 10:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brief_argument', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('petitioner_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Petitioner Name')),
                ('respodent_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Respondent Name')),
                ('legal_isse', models.TextField(blank=True, null=True, verbose_name='Legal Issue')),
                ('fact_case', models.TextField(blank=True, null=True, verbose_name='Fact of the Case')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('brief_argument', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='case_history', to='brief_argument.briefargument')),
            ],
        ),
    ]
