# Generated by Django 5.0.4 on 2024-06-02 08:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brief_argument', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HighCourts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CaseHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('petitioner_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Petitioner Name')),
                ('respondent_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Respondent Name')),
                ('legal_issue', models.TextField(blank=True, null=True, verbose_name='Legal Issue')),
                ('high_court', models.CharField(blank=True, max_length=255, null=True)),
                ('fact_case', models.TextField(blank=True, null=True, verbose_name='Fact of the Case')),
                ('submit_type', models.CharField(choices=[('petitioner', 'Petitioner'), ('respondent', 'Respondent')], max_length=20, null=True)),
                ('is_completed', models.BooleanField(blank=True, default=False, verbose_name='Is the email sent')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('brief_argument', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_history', to='brief_argument.briefargument')),
            ],
        ),
        migrations.CreateModel(
            name='LawTopics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('token_value', models.IntegerField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='case_history.lawtopics')),
            ],
        ),
    ]
