# Generated by Django 5.0.4 on 2024-05-13 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_history', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='casehistory',
            name='submit_type',
            field=models.CharField(choices=[('petitioner', 'Petitioner'), ('respondent', 'Respondent')], max_length=20, null=True),
        ),
    ]
