# Generated by Django 5.0.4 on 2024-06-03 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brief_argument', '0002_remove_briefargument_argument_value_and_more'),
        ('case_history', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='casehistory',
            name='legal_memo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_history', to='brief_argument.legal_memorandum'),
        ),
    ]
