# Generated by Django 5.0.4 on 2024-06-06 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case_history', '0002_casehistory_legal_memo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casehistory',
            name='brief_argument',
        ),
    ]
