# Generated by Django 5.0.4 on 2024-05-13 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brief_argument', '0001_initial'),
        ('case_history', '0002_casehistory_submit_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casehistory',
            name='brief_argument',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_history', to='brief_argument.briefargument'),
        ),
    ]
