# Generated by Django 5.0.4 on 2024-06-07 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_history', '0003_remove_casehistory_brief_argument'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawtopics',
            name='topic_id',
            field=models.CharField(blank=True, null=True),
        ),
    ]
