# Generated by Django 5.0.4 on 2024-05-14 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case_history', '0003_alter_casehistory_brief_argument'),
    ]

    operations = [
        migrations.RenameField(
            model_name='casehistory',
            old_name='legal_isse',
            new_name='legal_issue',
        ),
        migrations.RenameField(
            model_name='casehistory',
            old_name='respodent_name',
            new_name='respondent_name',
        ),
    ]
