# Generated by Django 5.0.4 on 2024-06-07 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_history', '0004_lawtopics_topic_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawtopics',
            name='topic_id',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
