# Generated by Django 5.0.4 on 2024-06-08 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_history', '0005_alter_lawtopics_topic_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casehistory',
            name='high_court',
        ),
        migrations.RemoveField(
            model_name='casehistory',
            name='petitioner_name',
        ),
        migrations.RemoveField(
            model_name='casehistory',
            name='respondent_name',
        ),
        migrations.RemoveField(
            model_name='casehistory',
            name='submit_type',
        ),
        migrations.AddField(
            model_name='casehistory',
            name='legal_research',
            field=models.TextField(blank=True, null=True, verbose_name='Legal Research'),
        ),
    ]
