# Generated by Django 5.0.4 on 2024-05-19 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_history', '0005_lawtopics'),
    ]

    operations = [
        migrations.AddField(
            model_name='casehistory',
            name='is_completed',
            field=models.BooleanField(blank=True, default=False, verbose_name='Is the email sent'),
        ),
    ]
