# Generated by Django 5.0.4 on 2024-05-20 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_history', '0006_casehistory_is_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='HighCourts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
