# Generated by Django 5.0.4 on 2024-06-08 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_history', '0006_remove_casehistory_high_court_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawtopics',
            name='topic_id',
            field=models.CharField(blank=True, null=True),
        ),
    ]
