# Generated by Django 5.0.4 on 2024-06-15 19:23

import pgvector.django
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_history', '0007_alter_lawtopics_topic_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalSearchHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('search_text', models.TextField(blank=True, null=True)),
                ('embeddings', pgvector.django.VectorField(dimensions=3072)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
