# Generated by Django 5.0.4 on 2024-06-02 08:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Argument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BriefArgument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('legal_principal', models.TextField(blank=True, null=True)),
                ('factual_analysis', models.TextField(blank=True, null=True)),
                ('case_name', models.TextField(blank=True, null=True)),
                ('relevant_topics', models.TextField(blank=True, null=True)),
                ('draft_argument', models.TextField(blank=True, null=True)),
                ('introduction', models.TextField(blank=True, null=True)),
                ('conclusion', models.TextField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('prayer', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('argument_value', models.ManyToManyField(related_name='brief_argument', to='brief_argument.argument')),
            ],
        ),
    ]
