# Generated by Django 5.0.4 on 2024-05-19 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brief_argument', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='argument',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='briefargument',
            name='case_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='briefargument',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='argument',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
