# Generated by Django 5.0.4 on 2024-06-03 08:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brief_argument', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='briefargument',
            name='argument_value',
        ),
        migrations.AddField(
            model_name='argument',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Legal_Memorandum',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('legal', models.TextField(blank=True, null=True)),
                ('facts', models.TextField(blank=True, null=True)),
                ('conclusion', models.TextField(blank=True, null=True)),
                ('relevant_topics', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('analysis', models.ManyToManyField(blank=True, related_name='legal_memo', to='brief_argument.argument')),
            ],
        ),
    ]
