# Generated by Django 5.0.4 on 2024-05-19 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brief_argument', '0002_argument_title_briefargument_case_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='briefargument',
            name='introduction',
            field=models.TextField(blank=True, null=True),
        ),
    ]
