# Generated by Django 5.0.4 on 2024-06-03 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brief_argument', '0002_remove_briefargument_argument_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legal_memorandum',
            name='analysis',
        ),
        migrations.AddField(
            model_name='argument',
            name='legal_memo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='brief_argument.legal_memorandum'),
        ),
    ]
