# Generated by Django 5.0.4 on 2024-06-04 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brief_argument', '0003_remove_legal_memorandum_analysis_argument_legal_memo'),
    ]

    operations = [
        migrations.AddField(
            model_name='legal_memorandum',
            name='full_legal_memo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='argument',
            name='legal_memo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='brief_argument.legal_memorandum'),
        ),
    ]
