# Generated by Django 5.0.4 on 2024-05-19 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brief_argument', '0003_briefargument_introduction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='briefargument',
            name='argument',
        ),
        migrations.AddField(
            model_name='argument',
            name='argument',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='argument', to='brief_argument.briefargument'),
        ),
    ]
