# Generated by Django 5.0.4 on 2024-06-05 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brief_argument', '0004_legal_memorandum_full_legal_memo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='argument',
            name='detailed_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DetailedAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('legal_memo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detailed_analysis', to='brief_argument.legal_memorandum')),
            ],
        ),
    ]
