# Generated by Django 5.0.4 on 2024-05-19 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brief_argument', '0004_remove_briefargument_argument_argument_argument'),
    ]

    operations = [
        migrations.RenameField(
            model_name='argument',
            old_name='argument',
            new_name='brief_argument',
        ),
    ]
