# Generated by Django 5.0.4 on 2024-05-19 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brief_argument', '0005_rename_argument_argument_brief_argument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='argument',
            name='brief_argument',
        ),
        migrations.AddField(
            model_name='briefargument',
            name='argument_value',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brief_argument', to='brief_argument.argument'),
        ),
    ]
