# Generated by Django 5.0.4 on 2024-06-06 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brief_argument', '0006_rename_full_legal_memo_legal_memorandum_full_legal_memo_html_and_more'),
        ('case_history', '0003_remove_casehistory_brief_argument'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BriefArgument',
        ),
        migrations.DeleteModel(
            name='DetailedAnalysis',
        ),
    ]
