# Generated by Django 5.0.4 on 2024-05-19 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brief_argument', '0006_remove_argument_brief_argument_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='briefargument',
            name='argument_value',
        ),
        migrations.AddField(
            model_name='briefargument',
            name='argument_value',
            field=models.ManyToManyField(blank=True, null=True, related_name='brief_argument', to='brief_argument.argument'),
        ),
    ]
