# Generated by Django 5.0.4 on 2024-05-19 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brief_argument', '0007_remove_briefargument_argument_value_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='argument',
            old_name='name',
            new_name='content',
        ),
    ]
