# Generated by Django 5.0.4 on 2024-05-25 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brief_argument', '0008_rename_name_argument_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='briefargument',
            name='argument_value',
            field=models.ManyToManyField(related_name='brief_argument', to='brief_argument.argument'),
        ),
    ]
