# Generated by Django 5.0.4 on 2024-06-06 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brief_argument', '0009_aib_exam_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='aib_exam',
            name='relevant_topics_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
