# Generated by Django 5.0.4 on 2024-06-11 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brief_argument', '0010_aib_exam_relevant_topics_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='HulsburyLawBooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.CharField(blank=True, null=True)),
                ('name', models.CharField(blank=True, null=True)),
                ('statement', models.TextField(blank=True, null=True)),
                ('citation_list', models.TextField(blank=True, null=True)),
                ('citation_value', models.TextField(blank=True, null=True)),
                ('unique_id', models.CharField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
