# Generated by Django 5.0.4 on 2024-06-15 10:53

import django.db.models.deletion
import pgvector.django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brief_argument', '0011_hulsburylawbooks'),
    ]

    operations = [
        pgvector.django.VectorExtension(),
        migrations.CreateModel(
            name='RelevantCitationsPassage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_name', models.TextField(blank=True, null=True)),
                ('passage', models.TextField(blank=True, null=True)),
                ('embeddings', pgvector.django.VectorField(dimensions=3000)),
                ('score', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('husbury_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relevant_passage', to='brief_argument.hulsburylawbooks')),
            ],
        ),
        migrations.CreateModel(
            name='StatementEmbeddings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embeddings', pgvector.django.VectorField(dimensions=3000)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('husbury_file', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statement_embeddings', to='brief_argument.hulsburylawbooks')),
            ],
        ),
    ]
