# Generated by Django 5.0.4 on 2024-06-15 13:35

import pgvector.django
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brief_argument', '0012_relevantcitations_statementembedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relevantcitationspassage',
            name='embeddings',
            field=pgvector.django.VectorField(dimensions=3072),
        ),
        migrations.AlterField(
            model_name='statementembeddings',
            name='embeddings',
            field=pgvector.django.VectorField(dimensions=3072),
        ),
    ]
