# Generated by Django 5.0.4 on 2024-06-19 12:30

import django.db.models.deletion
import pgvector.django
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brief_argument', '0013_alter_relevantcitationspassage_embeddings_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.TextField(blank=True, null=True)),
                ('court', models.CharField(blank=True, null=True)),
                ('judges', models.TextField(blank=True, null=True)),
                ('petitioner', models.CharField(blank=True, null=True)),
                ('respondent', models.CharField(blank=True, null=True)),
                ('citations', models.JSONField(blank=True, default=dict)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Caseparagraph',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('para_count', models.IntegerField(blank=True, null=True)),
                ('number', models.CharField(blank=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('embeddings', pgvector.django.VectorField(dimensions=3072)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paragraph', to='brief_argument.case')),
            ],
        ),
        migrations.CreateModel(
            name='CaseNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('short_text', models.TextField(blank=True, null=True)),
                ('long_text', models.TextField(blank=True, null=True)),
                ('embeddings', pgvector.django.VectorField(dimensions=3072)),
                ('para_number', models.CharField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_note', to='brief_argument.case')),
                ('paragraph', models.ManyToManyField(related_name='case_note', to='brief_argument.caseparagraph')),
            ],
        ),
    ]
