# Generated by Django 5.0.4 on 2024-06-19 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brief_argument', '0014_case_caseparagraph_casenote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casenote',
            name='embeddings',
        ),
        migrations.RemoveField(
            model_name='caseparagraph',
            name='embeddings',
        ),
    ]
