# Generated by Django 5.0.4 on 2024-06-30 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brief_argument', '0021_legal_memorandum_decision_conclusion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='legal_memorandum',
            name='brief_answer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
