# Generated by Django 5.0.4 on 2024-07-01 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brief_argument', '0022_legal_memorandum_brief_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='argument',
            name='final_legal_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='argument',
            name='index',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
