# Generated by Django 5.0.4 on 2024-07-13 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brief_argument', '0023_argument_final_legal_text_argument_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='case_references',
            field=models.ManyToManyField(blank=True, related_name='referring_cases', to='brief_argument.case'),
        ),
    ]
