# Generated by Django 5.0.4 on 2024-07-14 14:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brief_argument', '0024_case_case_references'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoCounsel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('legal_issue', models.TextField(blank=True, null=True, verbose_name='Legal Issue')),
                ('brief_facts', models.TextField(blank=True, null=True, verbose_name='Brief Facts')),
                ('case_facts', models.TextField(blank=True, null=True, verbose_name='Case Facts')),
                ('legal_research', models.TextField(blank=True, null=True, verbose_name='Legal Research')),
                ('research_analysis', models.TextField(blank=True, null=True, verbose_name='Research Analysis')),
                ('search_query', models.TextField(blank=True, null=True, verbose_name='Search Query')),
                ('is_completed', models.BooleanField(blank=True, default=False, verbose_name='Completed')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
