# Generated by Django 5.0.4 on 2024-07-16 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brief_argument', '0025_cocounsel'),
    ]

    operations = [
        migrations.AddField(
            model_name='cocounsel',
            name='case_ids_list',
            field=models.TextField(blank=True, null=True, verbose_name='Case Ids'),
        ),
        migrations.AddField(
            model_name='cocounsel',
            name='citations',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
