# Generated by Django 5.0.4 on 2024-07-18 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brief_argument', '0026_cocounsel_case_ids_list_cocounsel_citations'),
    ]

    operations = [
        migrations.AddField(
            model_name='cocounsel',
            name='scrape_link',
            field=models.URLField(blank=True, null=True, verbose_name='Scrapping Link'),
        ),
    ]
